//
//  FlagImage.swift
//  ReadyRemitSDK
//
//  Copyright © 2021 Brightwell. All rights reserved.
//
import UIKit


struct FlagImage {
  
  static let currencyFlagMap = [
        "AED": "ARE",
        "AFN": "AFG",
        "ALL": "ALB",
        "AMD": "ARM",
        "ANG": "ANT",
        "AOA": "AGO",
        "ARS": "ARG",
        "AUD": "AUS",
        "AWG": "ABW",
        "AZN": "AZE",
        "BAM": "BIH",
        "BBD": "BRB",
        "BDT": "BGD",
        "BGN": "BGR",
        "BHD": "BHR",
        "BIF": "BDI",
        "BMD": "BMU",
        "BND": "BRN",
        "BOB": "BOL",
        "BRL": "BRA",
        "BSD": "BHS",
        "BTN": "BTN",
        "BWP": "BWA",
        "BYN": "BLR",
        "BZD": "BLZ",
        "CAD": "CAN",
        "CDF": "COD",
        "CHF": "CHE",
        "CLP": "TCD",
        "CNY": "CHN",
        "COP": "COL",
        "CRC": "CRI",
        "CUP": "CUW",
        "CVE": "CPV",
        "CZK": "CZE",
        "DJF": "DJI",
        "DKK": "DNK",
        "DOP": "DOM",
        "DZD": "DZA",
        "EEK": "EST",
        "EGP": "EGY",
        "ERN": "ERI",
        "ETB": "ETH",
        "EUR": "N/A",
        "FJD": "FJI",
        "FKP": "FLK",
        "GBP": "GBR",
        "GEL": "GEO",
        "GHS": "GHA",
        "GIP": "GIB",
        "GMD": "GAB",
        "GNF": "GIN",
        "GTQ": "GTM",
        "GYD": "GUY",
        "HKD": "HKG",
        "HNL": "HND",
        "HRK": "HRV",
        "HTG": "HTI",
        "HUF": "HUN",
        "IDR": "IDN",
        "ILS": "ISR",
        "INR": "IND",
        "IQD": "IRQ",
        "IRR": "IRN",
        "ISK": "ISL",
        "JMD": "JAM",
        "JOD": "JOR",
        "JPY": "JPN",
        "KES": "KEN",
        "KGS": "KGZ",
        "KHR": "KHM",
        "KMF": "COM",
        "KPW": "PRK",
        "KRW": "KOR",
        "KWD": "KWT",
        "KYD": "CYM",
        "KZT": "KAZ",
        "LAK": "LAO",
        "LBP": "LBN",
        "LKR": "LKA",
        "LRD": "LBR",
        "LSL": "LSO",
        "LTL": "LTU",
        "LVL": "LVA",
        "LYD": "LBY",
        "MAD": "MAR",
        "MDL": "MDA",
        "MGA": "MDG",
        "MKD": "MKD",
        "MMK": "MMR",
        "MNT": "MNG",
        "MOP": "MAC",
        "MRO": "MRT",
        "MUR": "MUS",
        "MVR": "MDV",
        "MWK": "MWI",
        "MXN": "MEX",
        "MYR": "MYS",
        "MZN": "MOZ",
        "NAD": "NAM",
        "NGN": "NGA",
        "NIO": "NIC",
        "NOK": "NOR",
        "NPR": "NPL",
        "NZD": "NZL",
        "OMR": "OMN",
        "PAB": "PAN",
        "PEN": "PER",
        "PGK": "PNG",
        "PHP": "PHL",
        "PKR": "PAK",
        "PLN": "POL",
        "PYG": "PRY",
        "QAR": "QAT",
        "RON": "ROM",
        "RSD": "SRB",
        "RUB": "RUS",
        "SAR": "SAU",
        "SBD": "SLB",
        "SCR": "SYC",
        "SDG": "SDN",
        "SEK": "SWE",
        "SGD": "SGP",
        "SHP": "SHN",
        "SLL": "SLE",
        "SOS": "SOM",
        "SRD": "SUR",
        "SYP": "SYR",
        "SZL": "SWZ",
        "THB": "THA",
        "TJS": "TJK",
        "TMT": "TKM",
        "TND": "TUN",
        "TRY": "TUR",
        "TTD": "TTO",
        "TWD": "TWN",
        "TZS": "TZA",
        "UAH": "UKR",
        "UGX": "UGA",
        "USD": "USA",
        "UYU": "URY",
        "UZS": "UZB",
        "VEF": "VEN",
        "VND": "VNM",
        "VUV": "VUT",
        "WST": "WSM",
        "XAF": "CAF",
        "YER": "YEM",
        "ZAR": "ZAF",
        "ZMW": "ZMB",
        "ZWL": "ZWE",
        "TOP": "TON",
        "SSP": "SSD",
        "STN": "STP",
        "RWF": "RWA"
  ]
  
  static var fallback: UIImage {
    UIImage(namedSdk: "fallback")!
  }
  
  var image: UIImage
  
  init(countryIso3Code: String?) {
    switch countryIso3Code {
    case .none:
      image = Self.fallback
    case .some(let code):
      image = UIImage(namedSdk: code) ?? Self.fallback
    }
  }
  
  init(currencyIso3Code: String) {
    let countryCode = Self.currencyFlagMap[currencyIso3Code]
    self.init(countryIso3Code: countryCode)
  }
}
